### ISSUE TITLE
 SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?

### ISSUE THREAD

**Issue by sumit88** [motherapp/weight-csv-to-gfit#7]
Getting this error on 
google-fit-data>pip install -r requirements.txt
Collecting astroid==1.4.7 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7c/2e/7da23eb111f5086b607fd0fb813fa05932d4d8610f08eb8b9498f3d5628e/astroid-1.4.7-py2.py3-none-any.whl
Collecting google-api-python-client==1.5.1 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/e4/68/c78710d65b4503bf5d92c1bed96ba7bd49de33d0f453bdc40a7f241f6270/google_api_python_client-1.5.1-py2.py3-none-any.whl
Collecting httplib2==0.9.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/ff/a9/5751cdf17a70ea89f6dde23ceb1705bfb638fd8cee00f845308bf8d26397/httplib2-0.9.2.tar.gz
Collecting isort==4.2.5 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c3/0d/917971944e7da7f659e11efe7abf649f0e46c2d45edba2f6d9584ba15374/isort-4.2.5-py2.py3-none-any.whl
Collecting lazy-object-proxy==1.2.2 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/65/63/b6061968b0f3c7c52887456dfccbd07bec2303296911757d8c1cc228afe6/lazy-object-proxy-1.2.2.tar.gz
Collecting mccabe==0.5.0 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/59/a2/1382f6a41af561a12914bb3e79edef744872520db42f99347bcdc3af6bbc/mccabe-0.5.0-py2.py3-none-any.whl
Collecting oauth2client==2.2.0 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/5c/d6/42f18bd74bcc35b3579f08d8b7eb04ee8579b9b16a763b6505f8897c0d6e/oauth2client-2.2.0.tar.gz
Collecting pyasn1==0.1.9 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/69/be/e8946f7867b84b0e61a613f6fd56f63266190b1a470f945178f7cbc4d0ae/pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pyasn1-modules==0.0.8 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/10/93/4c08c4d435d42684e552b88a12332bd60a240bc440c29680c67461832cbb/pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pylint==1.6.4 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/92/f3/41deb50322d579517f779c3421b92f84133ddb6d954791bbd37aca1b5854/pylint-1.6.4-py2.py3-none-any.whl
Collecting python-dateutil==2.5.3 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/33/68/9eadc96f9899caebd98f55f942d6a8f3fb2b8f8e69ba81a0f771269897e9/python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting rsa==3.4.2 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Collecting simplejson==3.8.2 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/f0/07/26b519e6ebb03c2a74989f7571e6ae6b82e9d7d81b8de6fcdbfc643c7b58/simplejson-3.8.2.tar.gz
Collecting six==1.10.0 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting uritemplate==0.6 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/5a/6d/66aed916219c1a25e12a01457ea5442f80e54ed3844ef688b25e20dada5f/uritemplate-0.6.tar.gz
Collecting wrapt==1.10.8 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/00/dd/dc22f8d06ee1f16788131954fc69bc4438f8d0125dd62419a43b86383458/wrapt-1.10.8.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SUMIT~1.CHA\AppData\Local\Temp\pip-install-7uq6ucnp\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\SUMIT~1.CHA\AppData\Local\Temp\pip-install-7uq6ucnp\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\SUMIT~1.CHA\AppData\Local\Temp\pip-install-7uq6ucnp\wsgiref\
You are using pip version 19.0.1, however version 19.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\asd\google-fit-data>C:\asd\google-fit-data\venv\Scripts\pip install -r requirements.txt
Collecting astroid==1.4.7 (from -r requirements.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/7c/2e/7da23eb111f5086b607fd0fb813fa05932d4d8610f08eb8b9498f3d5628e/astroid-1.4.7-py2.py3-none-any.whl
Collecting google-api-python-client==1.5.1 (from -r requirements.txt (line 2))
  Using cached https://files.pythonhosted.org/packages/e4/68/c78710d65b4503bf5d92c1bed96ba7bd49de33d0f453bdc40a7f241f6270/google_api_python_client-1.5.1-py2.py3-none-any.whl
Collecting httplib2==0.9.2 (from -r requirements.txt (line 3))
  Using cached https://files.pythonhosted.org/packages/ff/a9/5751cdf17a70ea89f6dde23ceb1705bfb638fd8cee00f845308bf8d26397/httplib2-0.9.2.tar.gz
Collecting isort==4.2.5 (from -r requirements.txt (line 4))
  Using cached https://files.pythonhosted.org/packages/c3/0d/917971944e7da7f659e11efe7abf649f0e46c2d45edba2f6d9584ba15374/isort-4.2.5-py2.py3-none-any.whl
Collecting lazy-object-proxy==1.2.2 (from -r requirements.txt (line 5))
  Using cached https://files.pythonhosted.org/packages/65/63/b6061968b0f3c7c52887456dfccbd07bec2303296911757d8c1cc228afe6/lazy-object-proxy-1.2.2.tar.gz
Collecting mccabe==0.5.0 (from -r requirements.txt (line 6))
  Using cached https://files.pythonhosted.org/packages/59/a2/1382f6a41af561a12914bb3e79edef744872520db42f99347bcdc3af6bbc/mccabe-0.5.0-py2.py3-none-any.whl
Collecting oauth2client==2.2.0 (from -r requirements.txt (line 7))
  Using cached https://files.pythonhosted.org/packages/5c/d6/42f18bd74bcc35b3579f08d8b7eb04ee8579b9b16a763b6505f8897c0d6e/oauth2client-2.2.0.tar.gz
Collecting pyasn1==0.1.9 (from -r requirements.txt (line 8))
  Using cached https://files.pythonhosted.org/packages/69/be/e8946f7867b84b0e61a613f6fd56f63266190b1a470f945178f7cbc4d0ae/pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pyasn1-modules==0.0.8 (from -r requirements.txt (line 9))
  Using cached https://files.pythonhosted.org/packages/10/93/4c08c4d435d42684e552b88a12332bd60a240bc440c29680c67461832cbb/pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting pylint==1.6.4 (from -r requirements.txt (line 10))
  Using cached https://files.pythonhosted.org/packages/92/f3/41deb50322d579517f779c3421b92f84133ddb6d954791bbd37aca1b5854/pylint-1.6.4-py2.py3-none-any.whl
Collecting python-dateutil==2.5.3 (from -r requirements.txt (line 11))
  Using cached https://files.pythonhosted.org/packages/33/68/9eadc96f9899caebd98f55f942d6a8f3fb2b8f8e69ba81a0f771269897e9/python_dateutil-2.5.3-py2.py3-none-any.whl
Collecting rsa==3.4.2 (from -r requirements.txt (line 12))
  Using cached https://files.pythonhosted.org/packages/e1/ae/baedc9cb175552e95f3395c43055a6a5e125ae4d48a1d7a924baca83e92e/rsa-3.4.2-py2.py3-none-any.whl
Collecting simplejson==3.8.2 (from -r requirements.txt (line 13))
  Using cached https://files.pythonhosted.org/packages/f0/07/26b519e6ebb03c2a74989f7571e6ae6b82e9d7d81b8de6fcdbfc643c7b58/simplejson-3.8.2.tar.gz
Collecting six==1.10.0 (from -r requirements.txt (line 14))
  Using cached https://files.pythonhosted.org/packages/c8/0a/b6723e1bc4c516cb687841499455a8505b44607ab535be01091c0f24f079/six-1.10.0-py2.py3-none-any.whl
Collecting uritemplate==0.6 (from -r requirements.txt (line 15))
  Using cached https://files.pythonhosted.org/packages/5a/6d/66aed916219c1a25e12a01457ea5442f80e54ed3844ef688b25e20dada5f/uritemplate-0.6.tar.gz
Collecting wrapt==1.10.8 (from -r requirements.txt (line 16))
  Using cached https://files.pythonhosted.org/packages/00/dd/dc22f8d06ee1f16788131954fc69bc4438f8d0125dd62419a43b86383458/wrapt-1.10.8.tar.gz
Collecting wsgiref==0.1.2 (from -r requirements.txt (line 17))
  Using cached https://files.pythonhosted.org/packages/41/9e/309259ce8dff8c596e8c26df86dbc4e848b9249fd36797fd60be456f03fc/wsgiref-0.1.2.zip
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\SUMIT~1.CHA\AppData\Local\Temp\pip-install-97ry1rgc\wsgiref\setup.py", line 5, in <module>
        import ez_setup
      File "C:\Users\SUMIT~1.CHA\AppData\Local\Temp\pip-install-97ry1rgc\wsgiref\ez_setup\__init__.py", line 170
        print "Setuptools version",version,"or greater has been installed."
                                 ^
    SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Setuptools version",version,"or greater has been installed.")?
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in C:\Users\SUMIT~1.CHA\AppData\Local\Temp\pip-install-97ry1rgc\wsgiref\

**Comment by sumit88** [comment]
Can be solved by using python in the Script folder generated

**Comment by diliplj** [comment]
Hey i am having this problem too.. :( :(
